name: Continuous Integration workflow for Flutter apps

on:
  workflow_call:
    inputs:
      coverage-exclude:
        required: false
        type: string
        default: ''
        description: 'Patterns to add to the coverage exclude configuration. Must begin with a pipe (|) character!'
      test:
        required: false
        type: string
        default: ''
      pull-git-submodules:
        required: false
        type: boolean
        default: false
        description: 'Indicates whether this repository has Git submodules to pull.'

jobs:

  Integration-tests:
    if: ${{ inputs.test != '' }}
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.ACTION_SETTINGS_APP_ID }}
          private-key: ${{ secrets.ACTION_SETTINGS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: ${{ inputs.pull-git-submodules && 'recursive' || 'false' }}
          token: ${{ steps.app-token.outputs.token }}

      - name: Check whether integration test exists
        run: |
          if [ -f test/acceptance/driver/integration_test.dart ]; then
            echo "Integration test file located"
          else
            echo "Failed to find integration test file"
            exit 1
          fi

      - name: Configure Git for private repo access
        run: |
          git config --global url."https://x-access-token:${{ steps.app-token.outputs.token }}@github.com/".insteadOf "https://github.com/"
          
      - uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v2
        with:
          chrome-version: stable

      - name: Installing chromedriver (needed for Integration tests)
        uses: nanasess/setup-chromedriver@v2

      - name: Starting chromedriver and executing integration test
        run: |
          chromedriver --port=4444 &
          flutter pub get
          flutter drive --chrome-binary=${{ steps.setup-chrome.outputs.chrome-path }} --driver=test/acceptance/driver/integration_test.dart --target=test/acceptance/${{ inputs.test }}.dart -d web-server --dart-define=USE_MOCK_SERVICES=true

  Linter-UnitTest-SmokeTest-Build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.ACTION_SETTINGS_APP_ID }}
          private-key: ${{ secrets.ACTION_SETTINGS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checking out source code
        uses: actions/checkout@v6
        with:
          submodules: ${{ inputs.pull-git-submodules && 'recursive' || 'false' }}
          token: ${{ steps.app-token.outputs.token }}

      # -----------------------------------------------------------------------------------
      # ---------------------- Dev Container Pipeline -------------------------------------
      # -----------------------------------------------------------------------------------

      - name: Build and Run Dev Container
        id: container-pipeline
        uses: devcontainers/ci@v0.3
        with:
          push: never
          env: |
            GIT_TOKEN=${{ steps.app-token.outputs.token }}
          runCmd: |
            set -e
            
            # Configure access to internal Git repositories
            if [ -n "$GIT_TOKEN" ]; then 
              echo "Configuring git API token"
              git config --file /tmp/git-credentials \
                url."https://x-access-token:${GIT_TOKEN}@github.com/".insteadOf \
                "https://github.com/"
              export GIT_CONFIG_GLOBAL=/tmp/git-credentials
            fi
            
            echo "=== RESOLVING DEPENDENCIES ==="
            flutter pub get
            
            echo "=== RUNNING LINTS ==="
            # Runs both the flutter and dart linters, as they return different results sometimes
            # Both commands use `|| ...` so the build and test phase also runs
            flutter analyze . > lints.txt 2>&1 || LINTING_FAILED=true
            dart analyze . >> lints.txt 2>&1 || LINTING_FAILED=true
            
            # Deletes the lint output file if no failures were reported
            if [ ! -v LINTING_FAILED ]; then
              rm lints.txt
            fi
            
            echo "=== BUILDING WEB APP ==="
            if [ -f "lib/main.dart" ]; then
              flutter build web
            elif [ -f "example/lib/main.dart" ]; then
              (cd example && flutter pub get && flutter build web)
            fi
            
            echo "=== RUNNING TESTS ==="
            flutter test test/unit_tests test/widget --coverage

      # ---------------------------------------------------------------------------------------      
      # ---------------------- Pipeline Results Reporting -------------------------------------
      # ---------------------------------------------------------------------------------------    

      - name: Archive Lint Logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: lint-results
          path: lints.txt

      - name: Generate coverage report 
        uses: fermi-ad/code-coverage-reporter@v3
        with:
          include_pattern: ^.*\.dart$
          exclude_pattern: test/|\.dart_tool/${{ inputs.coverage-exclude }}

      - if: always()
        name: Report linting results
        run: |
          if [ -f lints.txt ]; then
            cat lints.txt
            exit 1
          fi
          echo "Linting and quality verifications passed cleanly!"
