name: Continuous Integration workflow for Rust apps

on:
  workflow_call:
    inputs:
      coverage-exclude:
        required: false
        type: string
        default: ''
        description: 'Patterns to add to the coverage exclude configuration. Must begin with a pipe (|) character!'
      pull-git-submodules:
        required: false
        type: boolean
        default: false
        description: 'Indicates whether this repository has Git submodules to pull.'
      references-internal-git-repo:
        required: false
        type: boolean
        default: false
        description: 'Indicates whether this repository has a dependency in its Cargo.toml that comes from an internal GitHub repo'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      # ------------------------------------------
      # --------------- Initial Setup ------------
      # ------------------------------------------

      - if: ${{ inputs.references-internal-git-repo }}
        name: Generate a token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          app-id: ${{ vars.ACTION_SETTINGS_APP_ID }}
          private-key: ${{ secrets.ACTION_SETTINGS_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: ${{ inputs.pull-git-submodules && 'recursive' || 'false' }}

      # ----------------------------------------------------------------
      # -------------------------- Build -------------------------------
      # ----------------------------------------------------------------

      - name: Build and Run Dev Container
        uses: devcontainers/ci@v0.3
        with:
          push: never
          env: |
            CARGO_NET_GIT_FETCH_WITH_CLI=${{ inputs.references-internal-git-repo }}
            GIT_TOKEN=${{ steps.app-token.outputs.token }}
          runCmd: |
            set -e
            
            # Configure access to internal Git repositories
            if [ -n "$GIT_TOKEN" ]; then 
              echo "Configuring git API token"
              git config --file /tmp/git-credentials \
                url."https://x-access-token:${GIT_TOKEN}@github.com/".insteadOf \
                "https://github.com/"
              export GIT_CONFIG_GLOBAL=/tmp/git-credentials
            fi
            
            echo "=== RUNNING LINTS ==="
            # Checks code conventions with clippy and format with cargo fmt
            # Both commands use `|| ...` so the build and test phase also runs
            RUSTFLAGS=-Wunused-crate-dependencies cargo clippy --all-targets --all-features -- -D warnings > lints.txt 2>&1 || LINTING_FAILED=true
            cargo fmt --all -- --check >> lints.txt 2>&1 || LINTING_FAILED=true
            
            # Deletes the lint output file if no failures were reported
            if [ ! -v LINTING_FAILED ]; then
              rm lints.txt
            fi
            
            echo "=== RUNNING TESTS ==="
            cargo llvm-cov --lcov --output-path target/lcov.info

      # ---------------------------------------------------------------------------------------      
      # ---------------------- Pipeline Results Reporting -------------------------------------
      # ---------------------------------------------------------------------------------------    

      - name: Archive Lint Logs
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: lint-results
          path: lints.txt

      - name: Generate coverage report
        uses: fermi-ad/code-coverage-reporter@v3
        with:
          coverage_file: target/lcov.info
          include_pattern: src/.*\.rs$
          exclude_pattern: target/${{ inputs.coverage-exclude }}

      - if: always()
        name: Report linting results
        run: |
          if [ -f lints.txt ]; then
            cat lints.txt
            exit 1
          fi
          echo "Linting and quality verifications passed cleanly!"
